# Configuration file version
apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
  - name: loki
    type: loki
    access: proxy
    url: http://loki:3100